services:
  #MongoDB
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db

  backend:
    build: . 
      # context: .
      # dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DB_URI=mongodb://mongo:27017
    depends_on:
      - mongo_db
    volumes:
      - .:/main
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo_db: {}